### PR TITLE
Added local cache

### PR DESCRIPTION
**Pull request by soccerGB**
The work in this PR was done by sethmoo.

### CODE REVIEW

**Comment by sethmoo** [comment]
This PR has the local cache changes, but is missing the second changeset in which the cache is integrated into the fetch.

@soccerGB, did you intend to make two PRs? If so, that's actually not a bad idea. I really like keeping changes separate.

**Comment by oprinmarius** [comment]
@soccerGB 
After https://github.com/Microsoft/Azure-DCAP-Client/pull/20  is merged , please rebase and run the tests again

**Comment by ionutbalutoiu** [comment]
Hello @soccerGB!

I found why the CI **fails** with this PR, but **succeeds** on the master branch.

In this PR, we have a new binary `tests` that is built by the `make check` target. As part of the CI testing, we build the Azure-DCAP-Client inside a Docker container (using base `ubuntu1604` Docker image). Unfortunately, due to the fact that Jenkins runs the command using the Jenkins user, the  `tests` binary gives segmentation fault when executed, because the Jenkins user is not present in the container. Snippet from the Jenkins log:
```
[Non-Simulation Container SGX1-FLC RelWithDebInfo] LD_LIBRARY_PATH=`dirname libdcap_quoteprov.so ` ./tests
[Non-Simulation Container SGX1-FLC RelWithDebInfo] Segmentation fault (core dumped)
```

Recall that this happens **ONLY** if you execute the `tests` binary inside a container with an unknown user. I fixed this by creating the Jenkins user in the Docker container image.

This is the pull request with my fix https://github.com/Microsoft/Azure-DCAP-Client/pull/24.

I already successfully validated this fix by adding it on top of your pull request [here](https://github.com/Microsoft/Azure-DCAP-Client/pull/22). And the CI is green! 

Please merge https://github.com/Microsoft/Azure-DCAP-Client/pull/24 and rebase this pull request on top of the new master branch.

Best regards,
Ionut

**Comment by ionutbalutoiu** [comment]
Hello,

Do we still need this PR after https://github.com/Microsoft/Azure-DCAP-Client/pull/23 got merged ?

Regards,
Ionut

**Pull request closed without merging**
